import ProductCard from '@/components/Cards/ProductCard'
import Banner from '@/components/Store/Banner'
import Head from 'next/head'

export default function Home({ products }) {

  return (
    <>
      <Head>
        <title>Store</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='mb-4'>
        <Banner />
        <div className="my-2 bg-light">
          <h4 className='text-center p-2 text-uppercase'>Products</h4>
        </div>
        <div className="row">
          {
            products?.map((item, i) => {
              return (
                <div key={i} className="col-lg-4">
                  <div className="mt-4">
                    <ProductCard product={item} />
                  </div>
                </div>
              )
            })
          }
        </div>
      </main>
    </>
  )
}

export async function getServerSideProps(context) {

  const response = await fetch('https://dummyjson.com/products');
  const result = await response.json();
  return {
    props: {
      products: result?.products
    }, // will be passed to the page component as props
  }
}